/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define PCR_IBE_ibe1 0x01u        /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe0 0x00u          /*!<@brief Pull Enable: Disables */
#define PCR_PS_ps1 0x01u          /*!<@brief Pull Select: Enables internal pullup resistor */
#define PORT5_PCR_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT5_8 (coord L14), MAX_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define MAX_INITIPINS_MAX_INT_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define MAX_INITIPINS_MAX_INT_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define MAX_INITIPINS_MAX_INT_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MAX_INITIPINS_MAX_INT_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define MAX_INITIPINS_MAX_INT_PIN 8U                   /*!<@brief PORT pin number */
#define MAX_INITIPINS_MAX_INT_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void MAX_InitIPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PWM_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
